# Generated by Django 4.2 on 2023-04-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
