# Generated by Django 4.2 on 2023-04-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0003_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
    ]
