# Generated by Django 4.2 on 2023-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0004_remove_user_surname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(editable=False, max_length=255, unique=True),
        ),
    ]
