# Generated by Django 4.2 on 2023-04-26 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0005_user_photo_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
