# Generated by Django 4.2 on 2023-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0006_user_birthday_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/profile"
            ),
        ),
    ]
