# Generated by Django 4.2 on 2023-04-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_order_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Об", "Обработка"), ("От", "Отправлен")],
                default="От",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="main.order",
            ),
        ),
    ]
